open https://pypi.org/project/colorlabels/
open https://pypi.org/project/color-lib/
open https://pypi.org/project/colorline/
open https://pypi.org/project/colorlog/
open https://pypi.org/project/color-log/
open https://pypi.org/project/colorlogger/
open https://pypi.org/project/colorlogs/
open https://pypi.org/project/colorlookup/
open https://pypi.org/project/colorlover/
open https://pypi.org/project/colormap/
open https://pypi.org/project/colormask/
open https://pypi.org/project/colormath/
open https://pypi.org/project/color-me/
open https://pypi.org/project/colormeshop/
open https://pypi.org/project/colormyprompt/
open https://pypi.org/project/colorname/
open https://pypi.org/project/color-names/
open https://pypi.org/project/colorobject/
open https://pypi.org/project/colorops/
open https://pypi.org/project/color-pal/
open https://pypi.org/project/colorpalette/
open https://pypi.org/project/color-pallete/
open https://pypi.org/project/colorpennester/
open https://pypi.org/project/colorpicker/
open https://pypi.org/project/colorprint/
open https://pypi.org/project/color-print/
open https://pypi.org/project/colorpro/
open https://pypi.org/project/colorpy/
open https://pypi.org/project/colorqrxy/
open https://pypi.org/project/colorsafe/
open https://pypi.org/project/colorscale/
open https://pypi.org/project/colorscheme/
open https://pypi.org/project/colorsep/
open https://pypi.org/project/colorshell/
open https://pypi.org/project/colorsnap/
open https://pypi.org/project/colorsnip/
open https://pypi.org/project/colorspace/
open https://pypi.org/project/colorspacious/
open https://pypi.org/project/colors-print/
open https://pypi.org/project/colors-py/
open https://pypi.org/project/color-ssh/
open https://pypi.org/project/color-string/
open https://pypi.org/project/colortable/
open https://pypi.org/project/colortater/
open https://pypi.org/project/color-temp/
open https://pypi.org/project/colorterm/
open https://pypi.org/project/colorthief/
open https://pypi.org/project/colorthis/
open https://pypi.org/project/colortips/
open https://pypi.org/project/color-tol/
open https://pypi.org/project/colortools/
open https://pypi.org/project/color-tracker/
open https://pypi.org/project/color-transfer/
open https://pypi.org/project/colortuple/
open https://pypi.org/project/colorutils/
open https://pypi.org/project/colorview2d/
open https://pypi.org/project/colorweave/
open https://pypi.org/project/colorworld/
open https://pypi.org/project/colorwrap/
open https://pypi.org/project/colory/
open https://pypi.org/project/colorz/
open https://pypi.org/project/colorzero/
open https://pypi.org/project/consolcolor/
open https://pypi.org/project/consolecolor/
open https://pypi.org/project/console-colors/
open https://pypi.org/project/coop-colorbox/
open https://pypi.org/project/cowtermcolor/
open https://pypi.org/project/cppcolormap/
open https://pypi.org/project/cp-to-anki-colorizer/
open https://pypi.org/project/csscolor/
