open https://pypi.org/project/odoo8-addon-website-mail-snippet-bg-color/
open https://pypi.org/project/odoo8-addon-web-tree-dynamic-colored-field/
open https://pypi.org/project/odoo8-addon-web-widget-color/
open https://pypi.org/project/odoo9-addon-web-editor-background-color/
open https://pypi.org/project/odoo9-addon-web-tree-dynamic-colored-field/
open https://pypi.org/project/odoo9-addon-web-widget-color/
open https://pypi.org/project/pandoc-latex-color/
open https://pypi.org/project/phylo-color/
open https://pypi.org/project/plonetheme-colorcontext/
open https://pypi.org/project/plonetheme-colorfulworld/
open https://pypi.org/project/pokecolors/
open https://pypi.org/project/primarycolors/
open https://pypi.org/project/py3color/
open https://pypi.org/project/pycolor/
open https://pypi.org/project/pycolorize/
open https://pypi.org/project/pycolorname/
open https://pypi.org/project/pycolors/
open https://pypi.org/project/pycolors2/
open https://pypi.org/project/pycolorsel/
open https://pypi.org/project/pycolorterm/
open https://pypi.org/project/pygments-ansi-color/
open https://pypi.org/project/pygments-colorizer/
open https://pypi.org/project/pyqtcolordialog/
open https://pypi.org/project/pytest-colordots/
open https://pypi.org/project/python-color-logger/
open https://pypi.org/project/python-colors/
open https://pypi.org/project/python-dpcolors/
open https://pypi.org/project/randomcolor/
open https://pypi.org/project/random-color/
open https://pypi.org/project/rcolors/
open https://pypi.org/project/recat-color/
open https://pypi.org/project/recolor-dots/
open https://pypi.org/project/rgbcolors/
open https://pypi.org/project/rio-color/
open https://pypi.org/project/rmcolor/
open https://pypi.org/project/rmcolors/
open https://pypi.org/project/searchcolor/
open https://pypi.org/project/shcolor/
open https://pypi.org/project/shcolors/
open https://pypi.org/project/show-color-beta/
open https://pypi.org/project/simple-colors/
open https://pypi.org/project/skilstak-colors/
open https://pypi.org/project/softcolor/
open https://pypi.org/project/string-colorizer/
open https://pypi.org/project/string-to-hex-color/
open https://pypi.org/project/stylelens-color/
open https://pypi.org/project/tailcolor/
open https://pypi.org/project/tamcolors/
open https://pypi.org/project/technicolor/
open https://pypi.org/project/technicolor-yawn/
open https://pypi.org/project/termcolor/
open https://pypi.org/project/termcolor2/
open https://pypi.org/project/termcolors/
open https://pypi.org/project/termcolor-util/
open https://pypi.org/project/terminalcolors/
open https://pypi.org/project/terminal-colors/
open https://pypi.org/project/tinycolor/
open https://pypi.org/project/tinycolor-py/
open https://pypi.org/project/tkcolorlist/
open https://pypi.org/project/tkcolorpicker/
open https://pypi.org/project/tmcolors/
open https://pypi.org/project/truecolor/
open https://pypi.org/project/twentytab-colorful/
open https://pypi.org/project/venstarcolortouch/
open https://pypi.org/project/wcolors/
open https://pypi.org/project/webcolors/
open https://pypi.org/project/word2color/
open https://pypi.org/project/xtermcolor/
open https://pypi.org/project/xtermcolors/
