open https://pypi.org/project/dash-color-picker/
open https://pypi.org/project/dash-colorscales/
open https://pypi.org/project/daycolor/
open https://pypi.org/project/descolors/
open https://pypi.org/project/dhcpkit-technicolor/
open https://pypi.org/project/django-admin-colors/
open https://pypi.org/project/django-colorbundle/
open https://pypi.org/project/django-color-captcha/
open https://pypi.org/project/django-colorfield/
open https://pypi.org/project/django-colorful/
open https://pypi.org/project/django-colorful-scybear/
open https://pypi.org/project/django-colors-formatter/
open https://pypi.org/project/django-easy-thumbnails-colorprofile/
open https://pypi.org/project/django-html5-colorfield/
open https://pypi.org/project/django-postgresql-rgb-colorfield/
open https://pypi.org/project/django-tinycolorpicker/
open https://pypi.org/project/dominantcolors/
open https://pypi.org/project/doscolors/
open https://pypi.org/project/dotcolors/
open https://pypi.org/project/easycolor/
open https://pypi.org/project/echocolor/
open https://pypi.org/project/equitable-coloring/
open https://pypi.org/project/extcolors/
open https://pypi.org/project/ezcolor/
open https://pypi.org/project/ezcolorizer/
open https://pypi.org/project/finder-colors/
open https://pypi.org/project/flake8-colors/
open https://pypi.org/project/four-color/
open https://pypi.org/project/ftw-colorbox/
open https://pypi.org/project/fullcolor/
open https://pypi.org/project/geneticocolor/
open https://pypi.org/project/gunicorn-color/
open https://pypi.org/project/htmlcolor/
open https://pypi.org/project/icolor/
open https://pypi.org/project/imagecolor/
open https://pypi.org/project/ipfcolor/
open https://pypi.org/project/iterm2-color-scheme/
open https://pypi.org/project/iterm-tab-color/
open https://pypi.org/project/js-bootstrap-colorpicker/
open https://pypi.org/project/js-jquery-colorpicker/
open https://pypi.org/project/js-jqueryui-syronex-colorpicker/
open https://pypi.org/project/jsoncolor/
open https://pypi.org/project/js-vanderlee-colorpicker/
open https://pypi.org/project/jupyter-qtconsole-colorschemes/
open https://pypi.org/project/l33tcolors/
open https://pypi.org/project/linecolor/
open https://pypi.org/project/logcat-color/
open https://pypi.org/project/logcolor/
open https://pypi.org/project/log-color/
open https://pypi.org/project/log-colorizer/
open https://pypi.org/project/log-colorizer-hook/
open https://pypi.org/project/logging-color-formatter/
open https://pypi.org/project/mac-colors/
open https://pypi.org/project/mappyfile-colors/
open https://pypi.org/project/matplotlib-colorbar/
open https://pypi.org/project/micropython-colorsys/
open https://pypi.org/project/mintty-colors/
open https://pypi.org/project/mlbcolors/
open https://pypi.org/project/nodebox-color/
open https://pypi.org/project/nosecolor/
open https://pypi.org/project/nose-colorxunit/
open https://pypi.org/project/odoo10-addon-web-editor-background-color/
open https://pypi.org/project/odoo10-addon-web-tree-dynamic-colored-field/
open https://pypi.org/project/odoo10-addon-web-widget-color/
open https://pypi.org/project/odoo11-addon-web-editor-background-color/
open https://pypi.org/project/odoo11-addon-web-tree-dynamic-colored-field/
open https://pypi.org/project/odoo11-addon-web-widget-color/
open https://pypi.org/project/odoo12-addon-web-widget-color/
open https://pypi.org/project/odoo8-addon-web-context-in-colors/
open https://pypi.org/project/odoo8-addon-web-option-auto-color/
