open https://pypi.org/project/3color-press/
open https://pypi.org/project/ansicolor/
open https://pypi.org/project/ansicolors/
open https://pypi.org/project/ansicolortags/
open https://pypi.org/project/ansitagcolor/
open https://pypi.org/project/apidev-coop-colorbox/
open https://pypi.org/project/argparse-color-formatter/
open https://pypi.org/project/autocolorize/
open https://pypi.org/project/bashcolor/
open https://pypi.org/project/bcolors/
open https://pypi.org/project/behave-plain-color-formatter/
open https://pypi.org/project/bob-ip-color/
open https://pypi.org/project/bob-ip-skincolorfilter/
open https://pypi.org/project/boxup-bicolormatrix/
open https://pypi.org/project/click-help-colors/
open https://pypi.org/project/clicolors/
open https://pypi.org/project/collective-colorbox/
open https://pypi.org/project/collective-js-colorpicker/
open https://pypi.org/project/collective-portlet-colorcollection/
open https://pypi.org/project/collective-threecolorstheme/
open https://pypi.org/project/collective-z3cform-colorpicker/
open https://pypi.org/project/color/
open https://pypi.org/project/coloralphabet/
open https://pypi.org/project/colorama/
open https://pypi.org/project/color-balance/
open https://pypi.org/project/colorboy/
open https://pypi.org/project/colorbrewer/
open https://pypi.org/project/colorcalendar/
open https://pypi.org/project/colorcells/
open https://pypi.org/project/colorcet/
open https://pypi.org/project/color-changer/
open https://pypi.org/project/colorclass/
open https://pypi.org/project/colorclassifier/
open https://pypi.org/project/colorconsole/
open https://pypi.org/project/colorcorrect/
open https://pypi.org/project/colordesk/
open https://pypi.org/project/color-detection/
open https://pypi.org/project/colordiffs/
open https://pypi.org/project/colorecho/
open https://pypi.org/project/colored/
open https://pypi.org/project/coloredlogger/
open https://pypi.org/project/coloredlogs/
open https://pypi.org/project/colorednoise/
open https://pypi.org/project/coloredprint/
open https://pypi.org/project/colored-slack-log-handler/
open https://pypi.org/project/coloredstring/
open https://pypi.org/project/colored-traceback/
open https://pypi.org/project/colorex/
open https://pypi.org/project/color-extraction/
open https://pypi.org/project/colorful/
open https://pypi.org/project/colorful-hieroglyph-theme/
open https://pypi.org/project/colorfulprinter/
open https://pypi.org/project/colorgram-py/
open https://pypi.org/project/colorguard/
open https://pypi.org/project/colorharmonies/
open https://pypi.org/project/colorhash/
open https://pypi.org/project/color-helpers/
open https://pypi.org/project/colorific/
open https://pypi.org/project/colorin/
open https://pypi.org/project/colorinche/
open https://pypi.org/project/colorio/
open https://pypi.org/project/colorise/
open https://pypi.org/project/colorit/
open https://pypi.org/project/colorize/
open https://pypi.org/project/colorizedlog/
open https://pypi.org/project/colorize-pinyin/
open https://pypi.org/project/colorize-py/
open https://pypi.org/project/colorizer/
open https://pypi.org/project/colorizer-py/
open https://pypi.org/project/colorlab/
